[versions]
agp = "8.4.0"
kotlin = "1.9.0"
lint = "31.4.0"

[libraries]
lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lint" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
